# Generated by Django 4.1.3 on 2023-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0003_alter_contactfm_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="staffinformation",
            fields=[
                (
                    "beltno",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("fname", models.CharField(default="", max_length=50)),
                ("lname", models.CharField(default="", max_length=50)),
                ("username", models.CharField(default="", max_length=50)),
                ("fathername", models.CharField(default="", max_length=50)),
                ("email", models.CharField(default="", max_length=50)),
                ("phoneno", models.CharField(default="", max_length=50)),
                ("cnic", models.CharField(default="", max_length=50)),
                ("rank", models.CharField(default="", max_length=50)),
                ("city", models.CharField(default="", max_length=50)),
                ("address", models.CharField(max_length=500)),
                ("station", models.CharField(default="", max_length=50)),
                ("division", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
