# Generated by Django 4.1.3 on 2023-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0005_criminalinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminalinformation",
            name="province",
            field=models.CharField(default="", max_length=50),
        ),
    ]
