# Generated by Django 4.1.3 on 2023-06-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0008_alter_criminalinformation_frontimg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="criminalrecord",
            fields=[
                (
                    "recordid",
                    models.AutoField(default="", primary_key=True, serialize=False),
                ),
                ("sublocality", models.CharField(default="NULL", max_length=50)),
                ("locality", models.CharField(default="NULL", max_length=50)),
                ("ctype", models.CharField(default="NULL", max_length=50)),
                ("detail", models.TextField(default="NULL", max_length=50)),
                ("city", models.CharField(default="NULL", max_length=50)),
                ("province", models.CharField(default="NULL", max_length=50)),
                (
                    "criminalid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cmssafex.criminalinformation",
                    ),
                ),
            ],
        ),
    ]
