# Generated by Django 4.1.3 on 2023-06-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0009_criminalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminalrecord",
            name="staffid",
            field=models.CharField(default="", max_length=50),
        ),
    ]
