# Generated by Django 4.1.3 on 2023-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0010_criminalrecord_staffid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criminalrecord",
            name="recordid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
