# Generated by Django 4.1.3 on 2023-07-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0012_remove_criminalinformation_leftimg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="detection",
            fields=[
                ("recordid", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(default="NULL", max_length=100)),
                ("datafile", models.ImageField(default="", upload_to="test/")),
            ],
        ),
    ]
