# Generated by Django 4.1.3 on 2023-07-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0013_detection"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="datatype",
            field=models.CharField(default="Image", max_length=50),
        ),
    ]
