# Generated by Django 4.1.3 on 2023-08-05 08:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0015_detection_detectedperson_detection_nooffaces_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="new_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="recordid",
                unique=True,
            ),
        ),
    ]
