# Generated by Django 4.1.3 on 2023-08-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0016_detection_new_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detection",
            old_name="new_slug",
            new_name="slug",
        ),
    ]
