# Generated by Django 4.1.3 on 2023-08-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmssafex", "0017_rename_new_slug_detection_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="outputvideo",
            field=models.FileField(default="", upload_to="detected/"),
        ),
    ]
